# Generated by Django 3.2.15 on 2022-09-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightName', models.CharField(default='Delta123', max_length=200)),
                ('Departing', models.CharField(max_length=100)),
                ('arriving', models.CharField(max_length=100)),
                ('DateArriving', models.DateField()),
                ('dateleaving', models.DateField()),
                ('TimeArriving', models.TimeField()),
                ('TimeLeaving', models.TimeField()),
            ],
        ),
    ]
