# Generated by Django 3.2.15 on 2022-10-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(unique=True)),
                ('flightName', models.CharField(max_length=30)),
                ('FlightID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherNumber', models.CharField(default='VA124', max_length=10)),
                ('reduction', models.IntegerField()),
            ],
        ),
    ]
