# Generated by Django 3.2.15 on 2022-10-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_bookedflights_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedflights',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
