# Generated by Django 3.2.15 on 2022-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_bookedflights_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedflights',
            name='UserID',
            field=models.IntegerField(),
        ),
    ]
