# Generated by Django 3.2.15 on 2022-10-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_bookedflights_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedflights',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
